### ISSUE TITLE
Reflect kick

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#1106]
Be angled towards the goal at the location the pass will arrive. Kick instantly when the ball sensor sees the ball (maybe put that code on robot itself)

**Comment by Floris-Hoek** [comment]
- ReflectKick does not work in simulation if "ignore invariants" is off.
The passer will get the ball and as soon as it has it will keep moving in the same direction and with the same speed as when it got there. The Skills in Getball are GoToPoss and Rotate. The GoToPoss skill is succesfull and the index in the statemachine is changed from 0 to 1. However, the tactic is reset for a reason I don't know right now which causes the skill to be GoToPos again.
- Passer passes the ball not far enough.
The passer does pass the ball if "ignore invariants" is on. The ShotType is set to PASS and because of this the kickpower is set to a value calculated using the distance to the Reflectorlocation and an "arbitrary" constant given in ControlUtils. The constant or calculation seems to be off because the passer passes the ball not far enough. It then again gets the ball and shoots again. This repeats until the passer is too close to the reflector to drive any further.
- The Passer misses the Reflector.
If the ShotType is set to MAX such that the ball can reach the Reflector, the Passer shoots the ball too far in front of the Reflector such that the ball just rolls past the Reflector.
