### ISSUE TITLE
Fix dealer

### ISSUE THREAD

**Issue by RobotJente** [RoboTeamTwente/roboteam_ai#1161]
The dealer showed some awkward behaviour during the testing period, with some suboptimal role assignments. It is important the dealer is clear and documented

**Comment by timovdk** [comment]
Edit: in Dealer.cpp, on development, change `costForProperty(true)` (line 148) to `costForProperty(false)` and then test :) 

I think this could have been fixed with the removal of the robotype. Apparently every not_important robot would get a score of 0.1 which is really good. Now, it gets a score of 30 which is like super bad. You can test origin/development for this
