### ISSUE TITLE
Allow AI InterfaceDrive to specify direction of driving

### ISSUE THREAD

**Issue by RobotJesse** [RoboTeamTwente/roboteam_ai#690]
We want to test strafing in order to evaluate different wheel configurations. This is currently hard to do with the AI interface, because it defaults to rotating the robot to the direction of the path, so the robot (almost) always travels the path facing forward. Instead of this, we want an option where we can control at what angle the robot should be rotated at (with respect to the frame of the global field) whilst following the path. 

Adding an option to specify which direction the robot should drive in would make it easier for control to test different wheel configurations.

Ideally we would like some sort of value between [-pi, pi] or something along those lines when we select interface driving. It should be discussed with control where we should put this option in the interface UI

**Comment by rolfvdhulst** [comment]
It´s probably actually easier to make a strategy that does this for you (e.g. drive in a square), where you can easily adjust the angle goToPos is driving at. Adding new interface handles means you have to mess around in lots of files and typically it is wiser to try to have not too many control options in the interface since it allows for more chances for human error. Also, the current interface drive uses NumTrees whilst you will a 100% want to use a simple PID controller for testing this behavior.
