### ISSUE TITLE
Segfault due to there not being enough stop-positions in stopformation

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_ai#731]
Encountered during replay of one of our matches (ER-force vs twente, at about 28:25 in the replay). The world sees 9 robots in formation and then Roboteam_AI segfaults in BallPlacementFormation::getFormationPosition(), line 49 since there is 9 robots but the vector is only 8 positions long. It happens about 50% of the time with our old world on master since it's not deterministic roflmao. This did not happen during the match since this code was made in an all nighter 2/3 nights later.

**Comment by mrlukasbos** [comment]
This is not entirely accurate. The vector is indeed only 8 robots long, and indeed sometimes 9 robots are seen. However, this bug was already present before the all-nighter in all formation skills. The segfault did not occur during games because there never have been more than 7 robots in the formation (1 is the keeper). Therefore this event is quite unlikely to happen.

Still this needs to be fixed of course by having some decent error handling.
